### ISSUE TITLE
podspec file need to update

### ISSUE THREAD

**Issue by MorganZhang100** [XCEssentials/UniFlow#2]
Hi Maxim,

On line 11 of "MKHUniFlow.podspec" file, the source_files directory seems wrong. You moved source files from "Src/Common/" to "Src/" but the source_files is still "Src/Common/". Could you update the podspec file?

Thanks,

Morgan

**Comment by mxkh72** [comment]
Right. Will do now.

**Comment by MorganZhang100** [comment]
Thanks a lot! :D

**Comment by mxkh72** [comment]
@MorganZhang100 I've updated source code under the same tag 1.1.1, check this out.

**Comment by MorganZhang100** [comment]
It seems 'Src/**/*.swift' doesn't work. 

Why not 'Src/*.swift'?
