### ISSUE TITLE
podspec file still not work

### ISSUE THREAD

**Issue by MorganZhang100** [XCEssentials/UniFlow#3]
It seems 'Src/**/*.swift' doesn't work.
Why not 'Src/*.swift'?

**Comment by mxkh72** [comment]
To find out "why" - check the Podspec file syntax. What do you mean by "doesn't work"? I jsut integrated MKHUniFlow in a test project - everything works as expected.

**Comment by mxkh72** [comment]
@MorganZhang100 so how it is going, have made it work?

**Comment by MorganZhang100** [comment]
I mean "doesn't work" by:
I add "pod 'MKHUniFlow', :git => 'https://github.com/maximkhatskevich/MKHUniFlow.git', :tag => '1.1.1'" in podfile.
After I run "pod install", no swift file is added into "/Pods/MKHUniFlow" dir. There are only 2 files under that dir. They are LICENCE and READEME.md. So the project couldn't find MKHUniFlow and will report this error to me when I hit "run".
I'm not sure if that's your or mine problem but I forked your project (the version that you just merge my PR) and import the MKHUniFlow from my github. Now it's working.

**Comment by mxkh72** [comment]
Up to you, but I would recommend add link to original repo of the library and run "pod update" instead of "install". When you run "install" it's not trying to re-install anything that has been already installed. I updated source files under the same tag, I told you about that. So that means there is no way for cocoapods to know that this pod needs to be updated unless you force update by "pod update".

**Comment by MorganZhang100** [comment]
I want to link to the original repo. Thanks for telling me the difference between "pod update" and "pod install". But before I run "pod install", I manually delete the whole "pods" dir. So I assume cocoapods should work properly. 
I will try to use "pod update".

**Comment by mxkh72** [comment]
Removing the pods dir does not affect the installation meta data that is stored in the "Podfile.lock" file. I would definitely recommend you to learn Cocoapods documentation for Podfile, it's not big at all, but will save you and people you deal with lots of time in future. https://guides.cocoapods.org/syntax/podfile.html

**Comment by MorganZhang100** [comment]
wow, I didn't know that. Thank you so much! I will learn that today.
